# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: My First Real Workflow

on:
  push:
    branches: ["main"]

jobs:
  My-Cool-Job:
    runs-on: ubuntu-latest
    env:
      working-directory: ./app/public

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: ./app/package-lock.json

      - run: ls
        working-directory: ${{env.working-directory}}
      - run: echo "hello World" >> someTexts.txt
        working-directory: ${{env.working-directory}}
      - run: ls
        working-directory: ${{env.working-directory}}
      - run: npm ci
        working-directory: ${{env.working-directory}}
      - run: npm run build --if-present
        working-directory: ${{env.working-directory}}
      - run: npm test
        working-directory: ${{env.working-directory}}

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: app/build # The folder the action should deploy.
